### ISSUE TITLE
Mbstring Requirement

### ISSUE THREAD

**Issue by matthewknill** [EFTEC/BladeOne#180]
I read that Mbstring is not required for this package, however, I run in to the following error (I don't have the Polyfill either):
```
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strpos() in /var/www/html/vendor/symfony/polyfill-mbstring/Mbstring.php:536
--
  | Stack trace:
  | #0 /var/www/html/vendor/symfony/polyfill-mbstring/bootstrap.php(64): Symfony\Polyfill\Mbstring\Mbstring::mb_strpos('component', '@', 0, 'UTF-8')
  | #1 /var/www/html/vendor/eftec/bladeone/lib/BladeOne.php(2870): mb_strpos('component', '@')
  | #2 /var/www/html/vendor/eftec/bladeone/lib/BladeOne.php(2828): eftec\bladeone\BladeOne::contains('component', '@')
  | #3 [internal function]: eftec\bladeone\BladeOne-&gt;eftec\bladeone\{closure}(Array)
  | #4 /var/www/html/vendor/eftec/bladeone/lib/BladeOne.php(2855): preg_replace_callback('/\\B@(@?\\w+(?:::...', Object(Closure), '@component('com...')
  | #5 /var/www/html/vendor/eftec/bladeone/lib/BladeOne.php(690): eftec\bladeone\BladeOne-&gt;compileStatements('@component('com...')
  | #6 /var/www/html/vendor/eftec/bladeone/lib/BladeOne.php(644): eftec\bladeone\BladeOne-&gt;parseToken(Array)
  | #7 /var/www/html/vendor/eftec/bladeone/l in <b>/var/www/html/vendor/symfony/polyfill-mbstring/Mbstring.php</b> on line <b>536</b><br />
```

**Comment by jorgecc** [comment]
afaik, it only uses the function if it is defined
```php
                if (\function_exists('mb_strpos')) {
                    if (\mb_strpos($haystack, $needle) !== false) {
                        return true;
                    }

```

**Comment by matthewknill** [comment]
@jorgecc why am I getting the error above then?

**Comment by jorgecc** [comment]
**symfony/polyfill-mbstring** is poly-filling it, so it calls its own function, and one of the functions lacks iconv_strpos
